### ISSUE TITLE
新增文章增加不了

### ISSUE THREAD

**Issue by dong200151** [WoodenStone/article_admin#6]
点击新增后，超时

**Comment by WoodenStone** [comment]
未复现成功，信息太少无法给出回答。

尝试：拉取最新代码并按照 readme 配置，依次检查数据库是否正常运行，node 服务是否正常启动，服务与数据库连接是否正常且能增删改查，前端与后端通讯是否正常；并根据具体报错信息排查。

**Comment by dong200151** [comment]
> 未复现成功，信息太少无法给出回答。
> 
> 尝试：拉取最新代码并按照 readme 配置，依次检查数据库是否正常运行，node 服务是否正常启动，服务与数据库连接是否正常且能增删改查，前端与后端通讯是否正常；并根据具体报错信息排查。

嗯嗯好，学的是html，怎么把你的项目转化成原生html呢，看不懂vue

**Comment by WoodenStone** [comment]
可以寻找纯 HTML + CSS + JavaScript 项目或在浏览 vue 文档后查看本项目： https://v2.cn.vuejs.org/   。
